export default {
  login: 'dfrost90',
  id: 15051700,
  node_id: 'MDQ6VXNlcjE1MDUxNzAw',
  avatar_url: 'https://avatars.githubusercontent.com/u/15051700?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/dfrost90',
  html_url: 'https://github.com/dfrost90',
  followers_url: 'https://api.github.com/users/dfrost90/followers',
  following_url: 'https://api.github.com/users/dfrost90/following{/other_user}',
  gists_url: 'https://api.github.com/users/dfrost90/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/dfrost90/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/dfrost90/subscriptions',
  organizations_url: 'https://api.github.com/users/dfrost90/orgs',
  repos_url: 'https://api.github.com/users/dfrost90/repos',
  events_url: 'https://api.github.com/users/dfrost90/events{/privacy}',
  received_events_url: 'https://api.github.com/users/dfrost90/received_events',
  type: 'User',
  site_admin: false,
  name: 'Dmitry Morozov',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 3,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: '2015-10-09T14:44:13Z',
  updated_at: '2023-02-15T18:20:45Z',
};
